/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminReportesRouteImport } from './routes/admin.reportes'
import { Route as AdminPanelRouteImport } from './routes/admin.panel'
import { Route as AdminMetricasRouteImport } from './routes/admin.metricas'
import { Route as AdminMapaRouteImport } from './routes/admin.mapa'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportesRoute = AdminReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPanelRoute = AdminPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMetricasRoute = AdminMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapaRoute = AdminMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/mapa': typeof AdminMapaRoute
  '/admin/metricas': typeof AdminMetricasRoute
  '/admin/panel': typeof AdminPanelRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/mapa': typeof AdminMapaRoute
  '/admin/metricas': typeof AdminMetricasRoute
  '/admin/panel': typeof AdminPanelRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/mapa': typeof AdminMapaRoute
  '/admin/metricas': typeof AdminMetricasRoute
  '/admin/panel': typeof AdminPanelRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/mapa'
    | '/admin/metricas'
    | '/admin/panel'
    | '/admin/reportes'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/mapa'
    | '/admin/metricas'
    | '/admin/panel'
    | '/admin/reportes'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/mapa'
    | '/admin/metricas'
    | '/admin/panel'
    | '/admin/reportes'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reportes': {
      id: '/admin/reportes'
      path: '/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AdminReportesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/panel': {
      id: '/admin/panel'
      path: '/panel'
      fullPath: '/admin/panel'
      preLoaderRoute: typeof AdminPanelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/metricas': {
      id: '/admin/metricas'
      path: '/metricas'
      fullPath: '/admin/metricas'
      preLoaderRoute: typeof AdminMetricasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mapa': {
      id: '/admin/mapa'
      path: '/mapa'
      fullPath: '/admin/mapa'
      preLoaderRoute: typeof AdminMapaRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminMapaRoute: typeof AdminMapaRoute
  AdminMetricasRoute: typeof AdminMetricasRoute
  AdminPanelRoute: typeof AdminPanelRoute
  AdminReportesRoute: typeof AdminReportesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMapaRoute: AdminMapaRoute,
  AdminMetricasRoute: AdminMetricasRoute,
  AdminPanelRoute: AdminPanelRoute,
  AdminReportesRoute: AdminReportesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
